# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('content', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=reviews.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('method', models.CharField(choices=[('FLOWER', 'FLOWER'), ('EXTRACT', 'EXTRACT'), ('EDIBLE', 'EDIBLE')], default='FLOWER', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Strain'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
