# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170320_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
