# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_strain_lineage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strain',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
