# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0016_auto_20180502_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='strains_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
