# Generated by Django 3.2 on 2022-05-29 09:30

from django.conf import settings
from django.db import migrations, models
import strains.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('lineage', models.JSONField(blank=True, null=True)),
                ('genetics', models.JSONField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=strains.models.upload_location1, width_field='width_field')),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('users_like', models.ManyToManyField(blank=True, related_name='strains_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
