# Generated by Django 3.2 on 2022-06-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='ocpc',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
