# Generated by Django 3.2 on 2022-06-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0005_auto_20220606_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='ocpc',
            field=models.CharField(max_length=160),
        ),
    ]
