# Generated by Django 3.2 on 2022-06-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0007_alter_strain_ocpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
