# Generated by Django 3.2 on 2022-06-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0008_strain_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='children',
        ),
    ]
