# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20170320_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
