# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170409_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='reviews.Strain'),
        ),
    ]
