# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20170410_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=reviews.models.upload_location1, width_field='width_field'),
        ),
    ]
