# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
