# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_strain_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='lineage',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
